### ISSUE TITLE
[COOK-4324] - Changing listen_addresses is not applied

### ISSUE THREAD

**Issue by someara** [sous-chefs/postgresql#115]
listen_addresses is one of the parameters in postgresql.conf that requires a full service restart to apply. However, the cookbook only does a service reload whenever the config file is changed. This causes fresh PostgreSQL servers, which default to listening only on localhost, to not be accessible to our application servers without manual tweaking.

**Comment by damacus** [comment]
Putting on hold as we need test kitchen 2.0 and the multiple passes ideally to test this works.

**Comment by damacus** [comment]
We now can converge multiple times using Test Kitchen.

**Comment by damacus** [comment]
I'm pretty sure this is fixed. If anyone is experiencing this *not* working. Please drop a new bug.
