### ISSUE TITLE
[COOK-3986] postgresql::config_pgtune doesn't update kernel.shmmax

### ISSUE THREAD

**Issue by hufman** [sous-chefs/postgresql#129]
postgresql::config_pgtune sets the shared_buffers setting in postgresql.conf to be a quarter of system ram, or sometimes one sixteenth of system ram. However, it does not change the kernel.shmmax value, which can cause Postgresql to fail to restart.

**Comment by martinisoft** [comment]
Unless we want to backport the fix @damacus which is likely going to involve adding the sysctl cookbook I think this issue can be closed since all recipes are being removed in the upcoming 7.0 release in favor of resources.
