### ISSUE TITLE
The server recipe should not try to set a password when database is a slave 

### ISSUE THREAD

**Issue by chr4** [sous-chefs/postgresql#132]
When using the postgresql cookbook for a slave database, the log gets spammed with the following errors

```
2013-10-11 08:07:43 CEST [8490] postgres@postgres ERROR: cannot execute ALTER ROLE in a read-only transaction
2013-10-11 08:07:43 CEST [8490] postgres@postgres STATEMENT: ALTER ROLE postgres ENCRYPTED PASSWORD '<passwd>';
```

One could simply add a

``` ruby
not_if "test -f #{node['postgresql']['config']['data_directory']}/recovery.conf"
```

But I think it would be cleaner to default to not setting a password for the postgres user (this is the default, as there's a pg_hba rule in place), and create an attribute if this is actually wanted:

``` ruby
node['postgresql']['server']['generate_password'] = true
```

**Comment by damacus** [comment]
This should still be possible using the new custom resource.

If you set the password to nil it'll not generate the password right now.

**Comment by damacus** [comment]
If you're still having this problem, let us know and we'll re-open this issue. 

Thanks!
