### ISSUE TITLE
Amazon Linux requires version of postgresql-server packet

### ISSUE THREAD

**Issue by marko-ciric** [sous-chefs/postgresql#218]
On Amazon Linux, when doing yum search postgresql-server, this is the response:
`======================================================== Matched: postgresql-server =========================================================
postgresql8.x86_64 : PostgreSQL client programs
postgresql8-server.x86_64 : The programs needed to create and run a PostgreSQL server
postgresql92.x86_64 : PostgreSQL client programs
postgresql92-server.x86_64 : The programs needed to create and run a PostgreSQL server
postgresql92-server-compat.x86_64 : PostgreSQL server config files for backward compatibility
postgresql93.x86_64 : PostgreSQL client programs
postgresql93-server.x86_64 : The programs needed to create and run a PostgreSQL server`

In attributes/default.rb : 
`default['postgresql']['server']['packages'] = %w{postgresql-server}`

While executing postgresql-server package without specifying a version, a first match from the list is installed (in this case postgresql8-server) which results in having postgresql 8.4 server always.

**Comment by CloCkWeRX** [comment]
This was probably fixed in #286 via pgdg support for amazon linux

**Comment by damacus** [comment]
@marko-ciric can you confirm this is fixed?

**Comment by damacus** [comment]
Closing as this has been pending contributor for a while now.
