### ISSUE TITLE
OpenSUSE: 'execute[/sbin/service postgresql initdb ]' error

### ISSUE THREAD

**Issue by gsaslis** [sous-chefs/postgresql#220]
Due to - what I believe is bug caused by a typo - on this line https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server_redhat.rb#L80 , my cook on an opensuse vm broke on line 82 (https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server_redhat.rb#L82) after upgrading from 3.4.2 to 3.4.14 .

**Comment by slyness** [comment]
Awesome. I will review this week.

**Comment by gsaslis** [comment]
@slyness : sorry for not replying earlier.. 
I think I should probably close #221, (no branch created, etc.) and open a new one for each of the two commits which i inadvertently included in the same PR.. what do you think?

**Comment by gsaslis** [comment]
also, as per the contrib guide ( https://github.com/hw-cookbooks/postgresql/blob/develop/CONTRIBUTING.md ) I'm trying to run the tests (and then write some more) but I keep getting "No Chef resources found"... any pointers as to what i might be doing wrong / missing?

**Comment by gsaslis** [comment]
could we have this merged in guys?

please feel free to let me know if there's something extra I should be doing...  ; )

**Comment by slyness** [comment]
We are way behind right now on reviewing a merging items in this repository. I hope to spend some time on that today. Thanks for the continued feedback and PRs.

**Comment by gsaslis** [comment]
Sounds good!! Anything I can do to help, please don't hesitate to ask... ; )



—
Giorgos Saslis

**Comment by gsaslis** [comment]
@slyness I believe the `initdb` that was added in your bf7fd296b8143a23ad423e16cd7d7af18c45ee17 commit for SUSE systems should not be there. 
This is definitely true for Opensuse 13.1 and 13.2, but I am not sure if there are some other suse-family systems you had in mind?

In fact, the reason I had originally opened this issue was because of a typo in https://github.com/hw-cookbooks/postgresql/blob/v3.4.14/recipes/server_redhat.rb#82, causing it to be executed, when it shouldn't have been invoked at all. 

Please let me know and I'll be happy to open a relevant PR.

**Comment by damacus** [comment]
@gsaslis if this is still relevant, we'd love a PR for this feature.

**Comment by damacus** [comment]
I'm going to close this issue down now. 

If anyone would like to add OpenSUSE support to the cookbook, that would be great!
