### ISSUE TITLE
pg_hba.conf forces local ident permissions

### ISSUE THREAD

**Issue by chr4** [sous-chefs/postgresql#233]
No matter what is specified in the `pg_hba` attribute, the cookbook always deploys the following rule:

https://github.com/hw-cookbooks/postgresql/blob/0da4c9b92ab961780d6afb30cda4cf573bd3ed6e/templates/default/pg_hba.conf.erb#L30-L35

This seems like an anti-pattern, as it appears to the user that he has full control over the `pg_hba.conf` settings using the attribute, which is not the case. It's furthermore not possible to not set the local permissions, which could be a security issue (only a minor one though, as it is only affecting UNIX sockets).

I think the permission line can/ should be removed/ migrated to the default `pg_hba` attribute.

**Comment by kri5** [comment]
:+1:

**Comment by kri5** [comment]
Any news on this issue?

**Comment by slyness** [comment]
I will have time this week to work on this cookbook.

**Comment by opsline-derek** [comment]
Any news on this?

**Comment by chr4** [comment]
I've published a rewrite of this cookbook that fixes this issue: https://github.com/chr4-cookbooks/postgresql (at least for me).
It only works for Trusty and Xenial at the moment, though.
