### ISSUE TITLE
config_pgtune uses ceil

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [sous-chefs/postgresql#310]
I have observed an issue, where the ceil method is rounding up the result:
https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/config_pgtune.rb#L197

system memory in KB / converted to MB / connections
2050008 / 1024 / 500.0  = 4.002
4.002 ceiling = 5MB

And that is what ends up in postgresql.conf
work_mem = '5MB'

Therefore, work_mem \* connections  is now over 100% of memory

**Comment by damacus** [comment]
hi @gabrielcrowdtilt do you have any decent way of testing this? 

We've love a reproducible test for this. 

Please reopen if this isn't fixed in master.
