### ISSUE TITLE
pgtune issue when running 9.5

### ISSUE THREAD

**Issue by jwmarshall** [sous-chefs/postgresql#331]
Noticed an issue with the `config_pgtune` recipe when running postgres 9.5. Basically `checkpoint_segments` is no longer a valid configuration option and will cause postgres to fail on restart.

```
    ================================================================================
    Error executing action `restart` on resource 'service[postgresql]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /etc/init.d/postgresql restart ----
    STDOUT: * Restarting PostgreSQL 9.5 database server
     * The PostgreSQL server failed to start. Please check the log output:
    LOG:  unrecognized configuration parameter "checkpoint_segments" in file "/etc/postgresql/9.5/main/postgresql.conf" line 8
    FATAL:  configuration file "/etc/postgresql/9.5/main/postgresql.conf" contains errors
       ...fail!
    STDERR:
    ---- End output of /etc/init.d/postgresql restart ----
    Ran /etc/init.d/postgresql restart returned 1
```

One option to fix this would be to wrap the line in the recipe with a conditional such that it doesn't add `checkpoint_segments` to the node defaults. There are of course new variables that should be tuned as well, like `max_wal_size`.

```
# postgresql 9.5 does away with checkpoint_segments, instead consider tuning min_wal_size, max_wal_size
# http://www.postgresql.org/docs/9.5/static/wal-configuration.html
unless node['postgresql']['version'] == '9.5'
  node.default['postgresql']['config']['checkpoint_segments'] = checkpoint_segments
end
```

I know that you guys have a thread open about postgres 9.5 support so I'm wondering if a PR to fix this would even be accepted, and if so is it worth my investigating and adding tuning options for the new variables. For now I'm manually tuning this stuff, which isn't a big deal.

Thanks for a great cookbook BTW, I've used it everywhere I've needed a postgres install.

**Comment by sunggun-yu** [comment]
+1

**Comment by Vasencheg** [comment]
+1

**Comment by vlabs** [comment]
+1

**Comment by tas50** [comment]
Fixed on master
