### ISSUE TITLE
Support for CentOS 6.5

### ISSUE THREAD

**Issue by onknows** [sous-chefs/postgresql#333]
Running this on CentOS 6.5 box will create a PostgreSQL installation that does not start. 

The service fails to start, there are no message. Other than [failed].

Will CentOS 6.5 be supported? Or is this too old.

**Comment by fletchowns** [comment]
I had to revert back to 3.2.18 on our CentOS 6.5 boxes, since I ran into issues with 3.2.24. Haven't had a chance to investigate further or try 4.0.2 yet.

**Comment by damacus** [comment]
Closing this as it's an old issue with few details. 

Once we've got the full rewrite out it'd be great to get  some more information
