### ISSUE TITLE
CentOS 7.2 (and similar) does not work

### ISSUE THREAD

**Issue by ares** [sous-chefs/postgresql#340]
getting authentication issue

```
    PG::ConnectionBad
    -----------------
    FATAL:  Ident authentication failed for user "postgres"
```

On CentOS 7.2+ I have to manually set the version to empty string since data is now in `/var/lib/pgsql/data` (not under version dir). I guess [this](https://github.com/hw-cookbooks/postgresql/blob/develop/attributes/default.rb#L178-L193) needs fixing.

**Comment by bcentinaro** [comment]
Actually the problem seems to be [this](https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server.rb#L54-L65). 

I'm not sure why the recipe itself seems to be overwriting the default attributes, but I assume there are reasons. 

I managed to get around this by using `node.force_override[:postgresql][:dir] = '/var/lib/pgsql/data'`

**Comment by mbacchi** [comment]
On CentOS 7.0 the recipe fails similarly.  If you provide no version, postgres 9.2 packages are installed but a random 8.4 directory is created:

```
[vagrant@localhost ~]$ rpm -qa | grep postgres
postgresql-libs-9.2.15-1.el7_2.x86_64
postgresql-9.2.15-1.el7_2.x86_64
postgresql-server-9.2.15-1.el7_2.x86_64
postgresql-devel-9.2.15-1.el7_2.x86_64
[vagrant@localhost ~]$ sudo ls /var/lib/pgsql/
8.4  backups  data  initdb.log
[vagrant@localhost ~]$ cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core) 
```

If you set the version to 9.2 (which is available in the updates repo) it fails to install version 8.4:

```
==> default: Recipe: postgresql::client
==> default:   * yum_package[postgresql84-devel] action install
==> default: 
==> default:     * No candidate version available for postgresql84-devel
==> default: 
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'yum_package[postgresql84-devel]'
==> default:     ================================================================================
```

Would be nice to have this working correctly, I actually tested 4.0.0, which was mentioned in #313 to be fixed, but this clearly indicates it was not.

**Comment by damacus** [comment]
Hey! have either of you tried the newer custom resources on master yet? We'd love some feedback, before releasing a copy into the wider world. 

Even better, we'd really like a hand getting some of these features/bugs squashed. 

Happy new year! 
Dan

**Comment by ares** [comment]
sorry I no longer actively use this cookbook, deferring to @mbacchi

**Comment by damacus** [comment]
Cool, what're you using instead? (if anything)

**Comment by ares** [comment]
I'm looking into switching form Chef to Ansible, if that does not work well, chances are I'd be using this cookbook again :-)

**Comment by thommay** [comment]
(sorry to jump on this issue unrelatedly, but @ares I'd love to hear more about why you're thinking about switching. could you drop me an email at thom@chef.io ? )

**Comment by damacus** [comment]
Fixed now thanks to a number of PR's over the last week or two. Travis is now passing on those platforms 👍
