### ISSUE TITLE
[ v9.4 Debian]  `pg_createcluster` does not help to create the cluster with new 'data_directory'

### ISSUE THREAD

**Issue by chrisduong** [sous-chefs/postgresql#349]
Hi, 

I've created the wrapper cookbook which will install PostgreSQL in the non-default `data_directory`, using `apt-pgdg`.

I noticed that the resource `execute 'Set locale and Create cluster'` never been executed, because whenever we installed `postgresql-9.4`, it will trigger the script to create the "the default main cluster", with the config at **/etc/postgresql/9.4/main**, and the data at **/var/lib/postgresql/9.4/main**.

> Setting up postgresql-9.4 (9.4.7-1.pgdg14.04+1) ...
>   Creating new cluster 9.4/main ...
>     config /etc/postgresql/9.4/main
>     data   /var/lib/postgresql/9.4/main
>     locale en_US.UTF-8
>     socket /var/run/postgresql
>     port   5432
>   update-alternatives: using /usr/share/postgresql/9.4/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
> - Starting PostgreSQL 9.4 database server                                                                                                                           [ OK ]
>   Setting up postgresql-contrib-9.4 (9.4.7-1.pgdg14.04+1) ...
>   Setting up sysstat (10.2.0-1) ...
>   
>   Creating config file /etc/default/sysstat with new version
>   update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
>   Processing triggers for libc-bin (2.19-0ubuntu6.3) ...
>   Processing triggers for ureadahead (0.100.0-16) ...

I honestly have to no clue for this "execute resource".

```
execute 'Set locale and Create cluster' do
  command 'export LC_ALL=C; /usr/bin/pg_createcluster --start ' + node['postgresql']['version'] + ' main'
  action :run
  not_if { ::File.directory?('/etc/postgresql/' + node['postgresql']['version'] + '/main') }
end
```

We didn't pass `data_directory` to this resource and it never executes, unless we **remove** the "default cluster main" conf directory (/etc/postgresql/9.4/main) and also its default data_directory which has been already generated when we install **postgresql-9.4**

I think we can stick to use `initdb` tool as in the Redhat recipes. My wrapper cookbook worked with this way.

``` ruby
# Fake /mnt/disk0/
directory '/mnt/disk0'

# Suppose we create new_datadir with correct permission
## Fake /mnt/disk0/psql_data
new_datadir = '/mnt/disk0/psql_data'

# Disable auto-start
execute 'disable auto-start 1/2' do
  command 'echo exit 101 > /usr/sbin/policy-rc.d'
end

execute 'disable auto-start 2/2' do
  command 'chmod +x /usr/sbin/policy-rc.d'
end

# No restart
node.override['postgresql']['server']['config_change_notify'] = :reload
node.override['postgresql']['config']['data_directory'] = new_datadir

node['postgresql']['server']['packages'].each do |pg_pack|
  package pg_pack
end

directory new_datadir do
  owner 'postgres'
  group 'postgres'
  recursive true
end

# Create new cluster with new_datadir
execute 'create base database in data_directory' do
  user 'postgres'
  command 'PATH=$PATH:/usr/lib/postgresql/' \
    "#{node['postgresql']['version']}/bin initdb " \
    "#{node['postgresql']['config']['data_directory']}"
  not_if do
    ::FileTest.exist?(
      File.join(node['postgresql']['config']['data_directory'], 'PG_VERSION')
    )
  end
end

include_recipe 'postgresql::ruby'
include_recipe 'postgresql::server'

```

**Comment by allaire** [comment]
Same issue with https://github.com/hw-cookbooks/postgresql/issues/342 I think. 

postgresql cookbook v4 does not take into consideration the version attribute set in my role, and always install 9.3. This broke our server.

**Comment by damacus** [comment]
Relates to #430

**Comment by damacus** [comment]
Closing and tracking in #430 if this is incorrect, please comment and we'll reopen!
