### ISSUE TITLE
Unable to define the install root for the package

### ISSUE THREAD

**Issue by JGONGSQ** [sous-chefs/postgresql#352]
When I try to set the install root to a path, it does not work, here is the code in my recipe, hope someone could help. I want to install my postgresql under path '/data/db/postgresql/9.3'.

node.set['postgresql']['dir'] = '/data/db/postgresql/9.3'
include_recipe 'postgresql::server'

Cheers
James

**Comment by manuelmazzuola** [comment]
This cookbook is utterly broken

**Comment by luckymike** [comment]
@JGONGSQ the recipe you've included after setting the attribute is taking precedence and resetting it, see here: https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server.rb#L54-L65

I think if you use a higher attribute precedence level you'll get the result you're after.

**Comment by damacus** [comment]
If this is still an issue please comment and we'll look at reopening this.
