### ISSUE TITLE
403 error when downloading files directly from yum.postgresql.org

### ISSUE THREAD

**Issue by bdrust** [sous-chefs/postgresql#362]
It looks like the postgresql.org guys have disabled direct downloads from yum.postgresql.org that results in 403 errors like this:

`Recipe: postgresql::yum_pgdg_postgresql
         * remote_file[/tmp/kitchen/cache/pgdg-centos93-9.3-2.noarch.rpm] action create[2016-09-29T13:10:57+00:00] WARN: remote_file[/tmp/kitchen/cache/pgdg-centos93-9.3-2.noarch.rpm] cannot be downloaded from http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-2.noarch.rpm: 403 "Forbidden"`

Changes will be needed to the default['postgresql']['pgdg']['repo_rpm_url'] hash to reflect this.

https://www.postgresql.org/message-id/1475152591.24885.79.camel@gunduz.org

**Comment by bdrust** [comment]
I got around this for the time being by overriding the following:

node.override['postgresql']['pgdg']['repo_rpm_url']['9.3']['centos']['6']['x86_64']['url'] = "http://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/"

**Comment by damacus** [comment]
I'm 99% sure this is fixed in master and later releases of the cookbook. 

If this isn't the case please comment and we'll fix this!
