### ISSUE TITLE
PostgreSQL 9.6 support

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/postgresql#370]
Workaround for PostgreSQL 9.6 support:

```
  "postgresql": {
    "config": {
      "dynamic_shared_memory_type": "sysv"
    },
    "version": "9.6",
    "dir": "/etc/postgresql/9.6/main",
    "client": {
      "packages": ["postgresql-client-9.6","libpq-dev"]
    }, 
    "server": {
      "packages": ["postgresql-9.6"]
    },
    "contrib": {
      "packages": ["postgresql-contrib-9.6"]
    },
  }
```

**Comment by brauliobo** [comment]
+!

**Comment by nkadel-skyhook** [comment]
Postgresql 9.6 has apparently renamed the setup script from "postgresql-setup" to "postgresql96-setup". Some thought, and work, need to be applied to the attributes/default.rb to set this correctly.

**Comment by aried3r** [comment]
> Postgresql 9.6 has apparently renamed the setup script from "postgresql-setup" to "postgresql96-setup".

I cannot verify this, at least on Ubuntu 16.04 LTS. A quick google of `postgresql96-setup` suggests that this might only be the case for installs using `yum`.

What I can say is that using the configuration in the OP I was able to install PostgreSQL 9.6 on Ubuntu 16.04 LTS. I only left out the `"dynamic_shared_memory_type": "sysv"` portion after reading https://github.com/sous-chefs/postgresql/commit/0218940c29c91dc2cdc7d1fe91665dfb59b5d728.

**Comment by damacus** [comment]
If anyone in this thread would like to support a PR for this, it would be great!

**Comment by damacus** [comment]
Fixed in master, we now also support PG 10.
