### ISSUE TITLE
Postgresql::ruby execution error

### ISSUE THREAD

**Issue by sernapallyanurag** [sous-chefs/postgresql#380]
===================================================================
      Recipe Compile Error in /var/chef/cache/cookbooks/postgresql/recipes/server.rb
      ==================================================================
    
    
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
    
      execute[generate pg gem Makefile] (postgresql::ruby line 114) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
      ---- Begin output of PATH=$PATH:/usr/pgsql-8.4/bin /opt/chef/embedded/bin/ruby extconf.rb ----
      STDOUT: checking for pg_config... yes
      STDERR: Using config values from /usr/bin/pg_config
      *** extconf.rb failed ***
      Could not create Makefile due to some reason, probably lack of necessary
      libraries and/or headers.  Check the mkmf.log file for more details.  You may
      need configuration options.
    
      Provided configuration options:
            --with-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
            --with-pg
            --without-pg
            --enable-windows-cross
            --disable-windows-cross
            --with-pg-config
            --without-pg-config
            --with-pg_config
            --without-pg_config
            --with-pg-dir
            --without-pg-dir
            --with-pg-include
            --without-pg-include=${pg-dir}/include
            --with-pg-lib
            --without-pg-lib=${pg-dir}/lib
      /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (Runtim
    eError)
      You have to install development tools first.
            from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
            from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
            from extconf.rb:53:in `<main>'
      ---- End output of PATH=$PATH:/usr/pgsql-8.4/bin /opt/chef/embedded/bin/ruby extconf.rb ----
      Ran PATH=$PATH:/usr/pgsql-8.4/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1
    
      Cookbook Trace:
      ---------------
        /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:120:in `rescue in rescue in from_file'
        /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:80:in `rescue in from_file'
        /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
        /var/chef/cache/cookbooks/postgresql/recipes/server.rb:23:in `from_file'
    
      Relevant File Content:
      ----------------------
      /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:
    
      113:
      114:      lib_builder = execute 'generate pg gem Makefile' do
      115:        # [COOK-3490] pg gem install requires full path on RHEL
      116:        command "PATH=$PATH:/usr/pgsql-#{node['postgresql']['version']}/bin #{RbConfig.ruby} extconf.rb"
      117:        cwd ext_dir
      118:        action :nothing
      119:      end
      120>>     lib_builder.run_action(:run)
      121:
      122:      lib_maker = execute 'make pg gem lib' do
      123:        command 'make'
      124:        cwd ext_dir
      125:        action :nothing
      126:      end
      127:      lib_maker.run_action(:run)
      128:
      129:      lib_installer = execute 'install pg gem lib' do
    
      Platform:
      ---------
      x86_64-linux

    {
    "name": "rapid_linux",
    "chef_type" : "role",
    "default_attributes" : {},
    "json_class" : "Chef::Role",
      "run_list": [
        "recipe[yum-epel]", "recipe[build-essential]", "recipe[runit]", "recipe[selinux::disabled]", 
      "recipe[git]", "recipe[git::package]", "recipe[nodejs::nodejs_from_source]",     "recipe[mongodb::default]", "recipe[postgresql::ruby]",
      "recipe[postgresql::default]",  "recipe[postgresql::server]",
        "recipe[database::sonadb]",
      "recipe[yum::libcloud]",
      "recipe[git::git_checkout_linux]" , "recipe[jenkins::deploy_rapid_linux]"
      ]
    }

Even though the recipe is mentioned somewhere in the middle of run-list,  it executes at the to of the run-list. I am not clear why this is happening. This fails my complete run-list with error mentioned above

**Comment by Sliim** [comment]
:+1: 
I'm getting the same error, it is because `postgresql::ruby` do many things at compile time.. And all the dependencies are not met during the compile time (first provisioning).

Fixed by enforcing attribute `[build-essential][compile_time]` to `true` on the node, but this should be done here: https://github.com/sous-chefs/postgresql/blob/master/recipes/ruby.rb#L31-L32

**Comment by tas50** [comment]
So I've tested the current cookbook on several platforms and it looks like we're doing the right thing on all platforms and the PG gem is installed. It does have to fail before it installs, which is necessary to figure out the version / gem path information. If you see that the first time don't worry. It's odd but normal
