### ISSUE TITLE
pg_upgrade support

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/postgresql#385]
Would be really great to have automated PostgeSQL upgrade, something like [this](https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/providers/pg_upgrade.rb)

**Comment by damacus** [comment]
<3 PR?

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs
