### ISSUE TITLE
assign_postgres_password and random password

### ISSUE THREAD

**Issue by onknows** [sous-chefs/postgresql#386]
Code below work in progress but should it not also take in to account `node['postgresql']['assign_postgres_password']`? 

If I choose to assign a password, why still generate random password and save it?

IMHO when it comes to managing passwords, do we not prefer to manage passwords in a more generic way? Personally I prefer cookbooks that use plain attributes for secrets so that I can add my own preferred solution for managing those secrets, depending on the situation.  

```
  unless node.key?('postgresql') && node['postgresql'].key?('password') && node['postgresql']['password'].key?('postgres')
    node.normal_unless['postgresql']['password']['postgres'] = random_password(length: 20, mode: :base64)
    node.save
  end
```

**Comment by damacus** [comment]
This piece of code isn't in master anymore as we've moved to custom resources. 

If [this resource](https://github.com/sous-chefs/postgresql/commit/9bd4d4fa8fb3e871ea3ae303b02065a7d39252d7) doesn't work for you can you open another ticket please? (As it'll be related to the custom resource and it's easier to track new bugs that way!)

Thanks,
Dan
