### ISSUE TITLE
Release 5.2.0 broken Postgres 9.4 install on CentOS 7

### ISSUE THREAD

**Issue by mattcorey** [sous-chefs/postgresql#397]
I had a very simple cookbook working to install Postgres 9.4 on CentOS 7 (7.2 and 7.3) that is now failing with postgresql version 5.2.0.  The error I'm getting is that there is no available 9.4 package to download from YUM, and it looks like the relevant /etc/yum.repos.d entries are missing.  

Locking my cookbook to depend on 5.1.0 fixes my issue.

**Comment by tas50** [comment]
Sorry for the breakage. The fix is on master and I'm working on cleaning up master so I can release another version. Probably today.
