### ISSUE TITLE
This recipe is not creating a postgresql.conf 

### ISSUE THREAD

**Issue by mreith101** [sous-chefs/postgresql#403]
### Cookbook version
6.0.0

### Chef-client version

12.14.89

### Platform Details
6.5

### Scenario:

I'm trying to install PostgreSQL into a custom folder /var/lib/pgsql/9.5

### Steps to Reproduce:

Running chef-client and including: 

include_recipe "postgresql::server" (in a wrapper cookbook) is installing ok but isn't creating a postgresql.conf

node.override['postgresql']['config']['listen_addresses'] = 'fake1local' an attribute override that I set for a test case.

### Expected Result:

Exepect postgresql.conf of any form (preferably with my custom changes) in /var/lib/pgsql/9.5

### Actual Result:

PostgreSQL fails to start because the configuration file isn't being generated properly.

**Comment by damacus** [comment]
Fixed by #481 .
