### ISSUE TITLE
PostgresqlHelpers#locale_date_order broken

### ISSUE THREAD

**Issue by jesperrojestal** [sous-chefs/postgresql#418]
### Cookbook version
6.0.1

### Scenario:
Trying to get it to return ymd order of date for sv_SE on Linux systems

### Steps to Reproduce:
```shellsession
# export LANG='sv_SE.UTF-8'
# chef-shell-z
chef (12.19.36)> include Opscode::PostgresqlHelpers
 => Object
chef (12.19.36)> locale_date_order
 => "mdy"
```

### Expected Result:
Expected to get "ymd" on linux (my local osx uses "dmy" for some reason after 1 hour of scratching my head.). Looking into the code first it uses `elseif` instead of `elsif` which makes it always return 'mdy' due to `elseif` is not a valid statement and will never make the if statement branch. Also it uses DateTime#strftime to get proper date format but it appears that the ruby`strftime` ignores LC_TIME locale and always outputs POSIX formatted:

```ruby
ENV['LANG']
=> "sv_SE.UTF-8"
Time.now.strftime('%x')
 => "03/02/17"
`date +%x`
 => "2017-03-02\n"
   ```

a simple solution is to replace DateTime#strftime with a call to /bin/date on posix systems:
```ruby
`/bin/date -d '2033-11-22' +%x`
```

**Comment by damacus** [comment]
Hey! 

Thanks for the bug report. 
Do you fancy submitting a PR for this issue?
