### ISSUE TITLE
postgresql-setup initdb postgresql-9.2: No such file or directory - postgresql-setup

### ISSUE THREAD

**Issue by alrf** [sous-chefs/postgresql#428]
### Cookbook version
v6.1.1

### Chef-client version
12.7

### Platform Details
CentOS 7.3

### Scenario:
I'm installing postgresql92 on CentOS 7:
include_recipe "postgresql"
include_recipe "postgresql::server"
include_recipe "postgresql::ruby"

### Steps to Reproduce:
include_recipe "postgresql"
include_recipe "postgresql::server"
include_recipe "postgresql::ruby"

### Expected Result:
Postgresql should be installed.

### Actual Result:
```
[2017-06-01T04:13:57-04:00] ERROR: execute[postgresql-setup initdb postgresql-9.2] (postgresql::server_redhat line 115) had an error: Errno::ENOENT: No such file or directory - postgresql-setup
[2017-06-01T04:13:59-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```
These lines from cookbook:
```
115:     execute "#{node['postgresql']['setup_script']} initdb #{svc_name}" do
116:       not_if { ::File.exist?("#{node['postgresql']['config']['data_directory']}/PG_VERSION") }
117:     end
118:   end

```

From attributes:
default['postgresql']['setup_script'] = 'postgresql-setup'

**There is no 'postgresql-setup' command for postgresql92.**

Commands output:
[root@linux ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@linux ~]#
[root@linux ~]# find / -name postgresql-setup
[root@linux ~]#
[root@linux ~]# rpm -qa | grep postgres
postgresql92-libs-9.2.21-1PGDG.rhel7.x86_64
postgresql92-server-9.2.21-1PGDG.rhel7.x86_64
postgresql92-9.2.21-1PGDG.rhel7.x86_64
postgresql92-devel-9.2.21-1PGDG.rhel7.x86_64
[root@linux ~]#

**Comment by teknofire** [comment]
@alrf are you setting any other attributes yourself?  

I see that the PGDG rpm packages are install which tells me that you have `node['postgresql']['enable_pgdg_yum'] = true` set.

If that is the case then you need to make sure to set all the other attributes as documented here: https://github.com/sous-chefs/postgresql#yum_pgdg_postgresql

Which also includes the setup script

**Comment by damacus** [comment]
Closing stale issue. Please re-open if it's still a problem!
