### ISSUE TITLE
Database Cookbook Deprecation Resolution

### ISSUE THREAD

**Issue by dmlb2000** [sous-chefs/postgresql#437]
### Cookbook version
The latest version of the [database](https://github.com/chef-boneyard/database) cookbook has been deprecated for a while stating they would try to move the resources for user and database management to the individual cookbooks.

Has this been done? What objections would there be moving what they have into this cookbook?

### Chef-client version
Latest
### Platform Details
Any
### Scenario:
Trying to manage users/databases in postgresql with chef.
### Steps to Reproduce:
N/A
### Expected Result:
Resources for managing users and databases in the postgresql cookbook.
### Actual Result:
Nothing has happened for months...

**Comment by gliptak** [comment]
There is also user handling code at https://github.com/phlipper/chef-postgresql/blob/master/providers/user.rb

**Comment by damacus** [comment]
We'd love some PRs for this!

**Comment by damacus** [comment]
Closing as this is an on going issue and project page is the best place to keep track of progress.

https://github.com/sous-chefs/postgresql/projects/1


Thanks! 
Dan
