### ISSUE TITLE
Password is saved on node/support for vault

### ISSUE THREAD

**Issue by clarklwilliamson** [sous-chefs/postgresql#443]
I the current version, 6.1.1, you specify the password as an attribute, and that saves it as a attribute on the chef server.

Can you add support for vaulted passwords?
Also with vaulted passwords, not save the password in the chef server?

**Comment by damacus** [comment]
Hi!

We've not released the latest version yet, but password should no longer get saved to the node via node attributes. 

Which vault type are you talking about? Chef or Hashicorp? 

Both should be possible now the server is installed via a custom resource. I don't have a Vault setup here, so if you'd be able to test `master` with Vault that'd be great!

**Comment by clarklwilliamson** [comment]
we are currently using chef vault but might possibly use hashicorp vault.

**Comment by damacus** [comment]
@clarklwilliamson  if you're still having this issue after the next major release of the cookbook, please reopen! 

If what's on master now doesn't work, we'd love a PR to help with this. 

Thanks, 
Dan
