### ISSUE TITLE
Only Support Non-EOL PostgreSQL

### ISSUE THREAD

**Issue by damacus** [sous-chefs/postgresql#449]
https://www.postgresql.org/support/versioning/

9.2 has just gone EOL 

```
9.2 | 9.2.23 | No | September 2012 | September 2017
```

**Comment by tas50** [comment]
Since we're moving to using the official repos I think this comes along for free. They don't have their EOL stuff there unless I missed something

**Comment by damacus** [comment]
This has also been documented in master now.
