### ISSUE TITLE
pg_gem resource needs better test for omnibus

### ISSUE THREAD

**Issue by lamont-granquist** [sous-chefs/postgresql#462]
https://github.com/sous-chefs/postgresql/blob/38a9f7fe959fc7f20abbc4d8281905b0740b70d5/resources/pg_gem.rb#L49-L54

that block of code is wrong.

if the distro has a pg lib then the chef_gem will succeed and will link against the distro pg libs, which will link against the distro openssl.  when the distro openssl tries to get loaded into the embedded ruby linked against the embedded openssl then everything explodes and it defeats the whole purpose of this recipe.

if the user is using omnibus then all the code in the rescue block must run -- the conditional needs to not be based on the chef_gem failing or not, but needs to be based on an `is_omnibus?` check.  the only reason this is working for some people right now is that they accidentally do not have distro support and/or their openssl lib version happens to match the
omnibus version.

**Comment by damacus** [comment]
thanks for pointing this one out @lamont-granquist it was mostly a late night copy 'n pasta.

I'll work on this one next as a priority.

**Comment by lamont-granquist** [comment]
Its been there as a bug for a long time i think

**Comment by damacus** [comment]
Indeed. The linked OpenSSL bug is a right nightmare. 

I'm quite tempted to remove the resource for now and it's unreliable as to what platforms it *currently* builds on.

**Comment by damacus** [comment]
So to fix this, I think we have a few options 

1) Install and configure pg_config with the lib_dir from Chef's embedded libs. 
2) Install `pg` gem using a non-Chef Ruby, which will link to the system libs correctly ([As described in this post ](https://bitbucket.org/ged/ruby-pg/issues/178/pgs-way-of-linking-to-openssl-is-not))

IMHO 1, is out of the question. Doing this would increase the complexity of the overall install process, and supportability of the cookbook. 

Option 2 seems more reasonable (and I've just got it working), but requires either the user or us to install a modern Ruby on the system (aka 2.0+) and then use that gem binary to install `pg`.

**Comment by lamont-granquist** [comment]
I'm not quite following you.

The outer block needs to be more like:

```
if RbConfig.ruby.scan(/(chef|opscode)/).empty?
  # not an omnibus install
  chef_gem "pg" do
    compile_time true
  end
else
  [ ... all the nasty stuff to link against omnibus ... ]
end
```

If you're omnibus, you never want to just do a `chef_gem` and try to link against the system.  If you're not omnibus you never want to do all the omnibus magic.

**Comment by damacus** [comment]
Forcing pg gem to link against the omnibus libraries all the time is, from my time looking into this, basically impossible.

You configure the pg gem and related libraries to link against a ssl library, by setting libdir in the postgresql config libdir setting.  
Sadly from what I can tell the libdir is only configurable at the time that postgresql is compiled.

**Comment by lamont-granquist** [comment]
oh lordy, i thought this built the pg libs as well as the pg gem...

**Comment by lamont-granquist** [comment]
So from the bug report:

```
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pg-0.21.0/lib/pg_ext.so is also linked against libssl.so.1.1 and libcrypto.so.1.1
```

That is only coming from the pg_gem.

So it may still work to link the pg_gem against the omnibus ruby (and the omnibus openssl) while against the system pg libs.  If there's no transitive dep (like the system pg libs depending on system openssl libs) then that will still work.  And that's the only way this code in this cookbook would have ever worked.

At any rate the complicated side of the codeblock here has worked for at least some people and distros in the past, and all I intended was to fix up the use case so that it tried to be correct as it could possibly be.

Right now its just fairly broken since if you're on omnibus you must always do the complicated side of the codeblock in order to link against the omnibus openssl libs.  Linking to the system libs only works in the cases where the openssl libs on the system and on omnibus are accidentally the same APIs.

**Comment by lamont-granquist** [comment]
So was there ever (like 3+ years ago?) a client.rb recipe which did a source install of the postgres libraries linking against the omnibus libs?  Because that is the missing piece here, and it may have gotten removed in some cookbook simplification and general streamlining to no longer support source compiles and only install packages from repos?

**Comment by lamont-granquist** [comment]
(still the bug here would need to get solved in the simply way that i outlined above)

**Comment by dayne** [comment]
In case others run into this issue and the related #480 issue (_which has a locked conversation so I can't toss this message there where these notes are likely more appropriate_)  and want to be able to move forward while a proper fix is found:

**A temporary work around:**

Remove the `pg` gem and reinstall `pg` gem against the install /usr/pgsql version this recipe had installed.  In my case I was on CentOS trying to install an older (9.3) version of postgresql:

`sudo /opt/chef/embedded/bin/gem uninstall pg`
`sudo /opt/chef/embedded/bin/gem install pg -v 0.21.0 -- --with-pg-config=/usr/pgsql-9.3/bin/pg_config`

That got me past the **uninitialized constant PGconn** error and right into a `psql: command not found` error that I was able to work past by doing this silly dance:
`sudo ln -s /usr/pgsql-9.3/bin/* /usr/local/bin`

None of this is very helpful in the broader sense and I look forward to a new version of this cookbook and the pg gem that don't have this issue.

**Comment by damacus** [comment]
Woo! 

Closing because we're getting rid of the resource ;)
