### ISSUE TITLE
Using with PostgreSQL 10

### ISSUE THREAD

**Issue by zepheiryan** [sous-chefs/postgresql#467]
### Cookbook version
6.1.1

### Chef-client version
12.19.36-1

### Platform Details
Ubuntu 16.04.3

### Scenario:
This is just a report on using the cookbook with PostgreSQL 10 in Ubuntu, which seems to work.

The only indication I saw that this cookbook would be compatible with 10 is the README note pointing to the official supported versions list, which is a change in master and not yet released.

Other than subbing in '10' in all the right spots and adding a few new config entries, is there anything else to account for?  Are the cookbook maintainers comfortable claiming compatibility at 6.1.1 with an application version officially released after the cookbook was released?  Or should users wait until another cookbook is released?

### Steps to Reproduce:

Node JSON excerpt:

```json
    "postgresql": {
      "enable_pgdg_apt": true,
      "version": "10",
      "dir": "/etc/postgresql/10/main",
      "server": {
        "service_name": "postgresql",
        "packages": [
          "postgresql-10"
        ]
      },
      "client": {
        "packages": [
          "postgresql-client-10",
          "libpq-dev"
        ]
      },
      "contrib": {
        "packages": null
      },
      "config": {
        "timezone": "UTC",
        "log_timezone": "UTC",
        "cluster_name": "10/main",
        "dynamic_shared_memory_type": "posix",
        "include_dir": "conf.d",
        "stats_temp_directory": "/var/run/postgresql/10-main.pg_stat_tmp",
        "lc_messages": "en_US.UTF-8",
        "lc_monetary": "en_US.UTF-8",
        "lc_numeric": "en_US.UTF-8",
        "lc_time": "en_US.UTF-8",
        "log_line_prefix": "%m [%p] %q%u@%d "
      }
    }
```

contrib appears to have been folded into postgresql-10.  config settings appear to be new or newly set, though I would guess some or all are the default when not explicitly set.

### Expected Result:
Things work.

### Actual Result:
...and they do!

**Comment by damacus** [comment]
Haha brilliant. Well we're switching to a newer resource driven model right now so updating the readme for that previous version would be irrelevant once we've finished this work.

Thanks for the report though!
