### ISSUE TITLE
PostgreSQL Extension Resource

### ISSUE THREAD

**Issue by damacus** [sous-chefs/postgresql#471]
## Feature
As a postgresql administrator
I want to install extensions listed [here](https://www.postgresql.org/docs/10/static/contrib.html)
So extensions are always installed in the state I expect

## Other Information
Notes from [create extension page](https://www.postgresql.org/docs/10/static/sql-createextension.html), 

Before you can use CREATE EXTENSION to load an extension into a database, the extension's supporting files must be installed. Information about installing the extensions supplied with PostgreSQL can be found in Additional Supplied Modules.

The extensions currently available for loading can be identified from the pg_available_extensions or pg_available_extension_versions system views.

**Comment by aleksandrs-ledovskis** [comment]
@damacus Just a note that you are referencing very old docs of PostgreSQL 9.1

**Comment by damacus** [comment]
@aleksandrs-ledovskis hah, thanks. Doesn't look like much/anything has changed thankfully. But amended to point to v10.0 instead.

**Comment by aleksandrs-ledovskis** [comment]
@damacus (Borderline finicky), but I still see first link pointing to 9.1

**Comment by damacus** [comment]
Cool fixed!

**Comment by damacus** [comment]
Fixed by #476
