### ISSUE TITLE
Use new inspec resources for tests

### ISSUE THREAD

**Issue by damacus** [sous-chefs/postgresql#478]
https://www.inspec.io/docs/reference/resources/postgres_conf/

https://www.inspec.io/docs/reference/resources/postgres_hba_conf/

https://www.inspec.io/docs/reference/resources/postgres_ident_conf/

<3 to whomever wrote these.

**Comment by damacus** [comment]
@YpNo we probably want to use these resources to test PG.

**Comment by damacus** [comment]
Relates to #500 #499 #498 #498 #497 #496

**Comment by YpNo** [comment]
@damacus I'm back :) I Will take it. I never use inspec yet. First try.

**Comment by aaronlippold** [comment]
No problem, glad you find them useful :)

@aaronlippold, @mdromazas, @rxaiver

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by martinisoft** [comment]
I've got some of these going in #517 though a word of warning, the connect one is host only so any peer level tests you need to still shell out to get a local socket connection instead of host.

**Comment by damacus** [comment]
We've used the corresponding tests where possible. 

Closed by #517
