### ISSUE TITLE
uninitialized constant PGconn

### ISSUE THREAD

**Issue by gionn** [sous-chefs/postgresql#480]
The [recently released pg gem](https://rubygems.org/gems/pg/versions/1.0.0) broke this cookbook (v6.1.1)

    NameError
    ---------
    uninitialized constant PGconn

Resolved with:

    default['postgresql']['pg_gem']['version'] = '0.21.0'

**Comment by damacus** [comment]
Cool! thanks. 

The pg_gem resource is generally broken, if you want to have a crack at fixing it properly and get it tested on all platforms that'd be great. 

See #462 for more information about the actual problem.

**Comment by gionn** [comment]
@jpeyret here we have a double combo bug: even if the gem compiling fails due to linking issues, after the first try, the recipe will go on without even trying anymore, hence the `uninitialized constant PGconn` error (uninitialized because there isn't any working library initializing it).

To recover a broken node I have manually removed chef-client package ( wiping everything under /opt/chef ) and then reinstalled again after setting the node attribute that fix this issue.

**Comment by chewi** [comment]
Off the top of my head, the quickest way to undo it is `sudo /opt/chef/embedded/bin/gem uninstall pg`.

**Comment by damacus** [comment]
Closing this issue now as we're removing the recipes & attributes in the upcoming release 

The default resource for pg_gem (once it's working) will install 0.21.0
