### ISSUE TITLE
Default Cookbook installs PostgreSQL Client 9.5

### ISSUE THREAD

**Issue by joshphp** [sous-chefs/postgresql#489]
### Cookbook version
6.1.1

### Chef-client version
13.6.4
### Platform Details
Ubuntu 16.04 (test kitchen) and EC2
### Scenario:
Wrapper cookbook calling 
`include_recipe 'postgresql'`
### Steps to Reproduce:
Create a wrapper cookbook with a default recipe including postgresql, and check the postgresql version after install. 
### Expected Result:
I was expecting version 9.6 per the README
### Actual Result:
Version 9.5 is installed

**Comment by joshphp** [comment]
So it looks like the 6.1.1 release is not up to date with the README on Master? 6.1.1 includes a recipes/ folder and therefore I need to reference it that way. Can you confirm if a new release is coming soon to match the docs?

**Comment by joshphp** [comment]
@YpNo I would say yes, but the README on master has information on how to use the cookbook version which has not been released yet. Unless I just am misunderstanding, but it is a bit confusing. I went back and confirmed on the supermarket that the info is correct there, it is just on master here where it is wrong.

**Comment by damacus** [comment]
Hi @joshphp 

we're still in the middle of shipping a number of features before we can cut a release, progress can be tracked via the [project board (roughly)](https://github.com/sous-chefs/postgresql/projects/1). 

We'll be posting to the Chef mailing list and announcing it on slack once it's ready ro ship. 

Hope that helps!

**Comment by damacus** [comment]
I'll close this issue down as it relates to an "older" version (be it the only one that's released), and isn't something we're going to fix before we ship another release.
