### ISSUE TITLE
Update user resource strips postgres user of SUPERUSER if you aren't careful.

### ISSUE THREAD

**Issue by jkugler** [sous-chefs/postgresql#509]
### Cookbook version
Master branch, unreleased

### Chef-client version
12.x

### Platform Details
Ubuntu 16.04

### Scenario:
User update resource strips postgres user of SUPERUSER privs

### Steps to Reproduce:
Run this:
```
pginstance_user 'set postgres password' do
  action :update
  user 'postgres'
  password 'somepass'
end
```

### Expected Result:
I expect the postgre user to have a password, and nothing else to change.

### Actual Result:
The update user resource includes NOSUPERUSER stripping the postgres user of its superuser properties.

Proposed solution: only modify user attributes which are explicitly set by the resource caller.

**Comment by jkugler** [comment]
Addendum: this will strip superuser from any user you update if you don't specify `superuser true`. Example:

```
pginstance_user 'create spiffy user' do
  action :create
  user 'spiffy'
  superuser true
end

pginstance_user 'set spiffy password' do
  action :update
  user 'spiffy'
  password 'myspiffypassword'
end
```
User spiffy will now no longer have superuser perms.

**Comment by damacus** [comment]
That's correct.

The default and safest default value for a user to have is *not* admin or super user. 

We've stated this in the readme [here](https://github.com/sous-chefs/postgresql/blob/master/README.md#postgresql user). 

I don't think this is a bug right now and is working as intended.

Thanks Dan

**Comment by jkugler** [comment]
Put another way, CREATE should default to superuser = false, but an update should have no default, and leave that property alone.

**Comment by jkugler** [comment]
Example: file resource in chef. The permissions on the file are not changed if it is not specified. A user's group is not changed if not specified in a call to the user resource.

**Comment by jkugler** [comment]
If this behavior is not going to be changed, then I would request that it gets called out with a VERY large warning in the docs. It was VERY surprising for a property I didn't modify to get modified. :)
