### ISSUE TITLE
Feedback: Major breaking changes upcoming, need some feedback

### ISSUE THREAD

**Issue by martinisoft** [sous-chefs/postgresql#512]
Hey everyone! I'm in the midst of doing a fair bit of reconstruction work on the cookbook which is slated for the 7.x release. The things it will do are:

* Chef 13.8+ compatibility. Since Chef 14 comes out in April and Chef 12 will be EOL at the end of April, it is time to move everything up.
* Drastically alter the way the cookbook works under the covers. For the longest time it was dependent on the pg gem which was no picnic to install into the Chef Omnibus and thus it has temporarily been removed from this upcoming release until there is a cleaner/better/testable solution. Now it is a series of shell outs to the postgres toolchain to directly manipulate systems.
* Re-factors the very extensive attributes away from the cookbook entirely. For a very long time this cookbook used the library cookbook anti-pattern that is attributes. Since you can technically have multiple versions of postgresql installed on a given system, the current way it is setup does not allow for you to manage all of those clusters. Going forward, the first (small) step to supporting clusters is to specify a version number. Not only does this correspond to package installs, but it also refers to the cluster name as well which on _most_ systems is named after the `PG_VERSION` that is present in those folders. A future refactor can take the postgres cluster scheme into better account. If you have a solid use case for this too, please open an issue so we can examine it and see how we can update the resources to account for it.
* Creates a lot more testing to verify correctness. There are now integration tests to cover all of the resources sometimes multiple times. This will slow down the overall test suite speed, but I'll trade test coverage for CI speed every day.
* Simplifies the library helpers and removes them from the global namespace. Forcing the postgres global helpers upon everyone is not a very nice thing to do so there will be examples and documentation on how to do this better in your wrapper cookbook.

Whew, yes this is one hell of a rewrite that needed to happen for the future maintainability of this cookbook. So, what I'd also like feedback on is how we roll this out to everyone using this cookbook. My idea for now is to cut a branch off the most recent 6 series release called 6.x then make a new patch version which adds a lot of `Chef::Log.warn`'s everywhere and some lengthy deprecation and migration documentation in the README. We can also leverage this branch to backport any more changes to make it Chef 13 compatible to buy users a bit more time to migrate up to the newer cookbook.

**Comment by damacus** [comment]
@florian-asche can you try again using the current master branch? 

Should be good to go now.

**Comment by florian-asche** [comment]
```
 * postgresql_user[fhem] action create
    * execute[create postgresql user fhem] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[create postgresql user fhem]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Command execution failed. STDOUT/STDERR suppressed for sensitive resource
      
      Resource Declaration:
      ---------------------
      suppressed sensitive resource output
      
      Compiled Resource:
      ------------------
      suppressed sensitive resource output
      
      System Info:
      ------------
      chef_version=13.8.5
      platform=ubuntu
      platform_version=16.04
      ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
      program_name=chef-solo worker: ppid=1907;start=01:01:14;
      executable=/opt/chef/bin/chef-solo
      
    
    ================================================================================
    Error executing action `create` on resource 'postgresql_user[fhem]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[create postgresql user fhem] (/root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/resources/user.rb line 33) had an error: Mixlib::ShellOut::ShellCommandFailed: Command execution failed. STDOUT/STDERR suppressed for sensitive resource
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/local-mode-cache/cache/cookbooks/own_fhem/recipes/create_db.rb
    
     41: postgresql_user node['fhem']['db']['user'] do
     42:   password node['fhem']['db']['password']
     43:   createdb false
     44:   #valid_until '2018-12-31'
     45: end
     46: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/own_fhem/recipes/create_db.rb:41:in `from_file'
    
    postgresql_user("fhem") do
      action [:create]
      default_guard_interpreter :default
      declared_type :postgresql_user
      cookbook_name "own_fhem"
      recipe_name "create_db"
      password "..."
      createdb false
    end
    
    System Info:
    ------------
    chef_version=13.8.5
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=chef-solo worker: ppid=1907;start=01:01:14;
    executable=/opt/chef/bin/chef-solo
    

```

**Comment by florian-asche** [comment]
A test for creating a database is missing.

**Comment by florian-asche** [comment]
Anything else looks like really really good work. Maybe some more documentation, but anyway with the kitchen test (taken as an example) and some looking into the code for variables like "locale" I was ready to go. Run was successful. Will test it tomorrow, if anything works like expected.

**Comment by florian-asche** [comment]
The default configuration (debian and yours looks different) i added this:

>     "additional_config": {
>       "port": 5432,
>       "max_connections": 100,
>       "superuser_reserved_connections": 3,
>       "unix_socket_directories": "/var/run/postgresql",
>       "ssl": "on",
>       "ssl_cert_file": "/etc/ssl/certs/ssl-cert-snakeoil.pem",
>       "ssl_key_file": "/etc/ssl/private/ssl-cert-snakeoil.key",
>       "shared_buffers": "128MB",
>       "dynamic_shared_memory_type": "posix",
>       "log_line_prefix": "%m [%p] %q%u@%d ",
>       "log_timezone": "localtime",
>       "cluster_name": "9.5/main",
>       "stats_temp_directory": "/var/run/postgresql/9.5-main.pg_stat_tmp",
>       "datestyle": "iso, dmy",
>       "timezone": "localtime",
>       "lc_messages": "de_DE.UTF-8",
>       "lc_monetary": "de_DE.UTF-8",
>       "lc_numeric": "de_DE.UTF-8",
>       "lc_time": "de_DE.UTF-8",
>       "default_text_search_config": "pg_catalog.german"
>     }

**Comment by damacus** [comment]
Thanks for the feedback! 

I'm closing this one down now in favour of new issues raised post 7.0
