### ISSUE TITLE
Remove run_state

### ISSUE THREAD

**Issue by damacus** [sous-chefs/postgresql#523]
### Cookbook version

`7.x`

### Scenario:

In the current version of the cookbook we share the version information via `node.run_state['postgresql']['version']`. 

This restricts us in several places to having one cluster and one config per installation. 

### Expected Result:

- I can create multiple pg clusters
- I can configure multiple pg clusters.

**Comment by josephholsten** [comment]
@martinisoft need anything from us? enabling the psql 10+ stuff sounds awesome!

**Comment by martinisoft** [comment]
> need anything from us? enabling the psql 10+ stuff sounds awesome!

Not really @josephholsten anyone else can pickup this issue. Might work on it in a couple weeks during a livestream.

**Comment by ramereth** [comment]
This cookbook no longer uses attributes.
