### ISSUE TITLE
Why was a major breaking change done as a minor version bump???

### ISSUE THREAD

**Issue by paustin01** [sous-chefs/postgresql#524]
Curious why a major refactor with breaking changes only deserved a minor version bump from 6.1.1 to 6.1.2? I can't be the only one who had this in my berksfile...

```
depends 'postgresql', '~> 6.1.1'
```
Obviously this breaks stuff if you're using recipes. We had inadvertently pushed 6.1.2 up to our chef server which broke a bunch of stuff. Easy to fix of course, just seems like it shouldn't have been an issue in the first place. Am I missing something?

**Comment by fletchowns** [comment]
I had to pin to 6.1.1 as well since it broke us, I figured 6.1.2 was just gonna be some deprecation warnings based on the changelog.

**Comment by fletchowns** [comment]
Looks like they have corrected it with 6.1.3: https://github.com/sous-chefs/postgresql/issues/522#issuecomment-381771316 (I haven't tried it out yet)

**Comment by leegarrett** [comment]
Since 6.1.3 is still incompatible to 6.1.1, I suggest to release 6.1.4 and revert it to the state of 6.1.1. And then push those breaking changes to 6.2.0. If you're using semantic versioning, it's a good idea to stick to the rules.

**Comment by paustin01** [comment]
What @leegarrett said for sure.

**Comment by damacus** [comment]
If everyone can pin to 6.1.1 for now. That would be great.

I'll see about getting 6.1.2 yanked from supermarket.

**Comment by damacus** [comment]
Thanks for the feedback everyone. The push to supermarket with this many changes was unintentional (obviously if you take the changelog at face value which you should in this case).

**Comment by leegarrett** [comment]
Thanks for the quick response. I wouldn't remove it from the supermarket though, because it will still be cached in everyone's ~/.berkshelf/cookbook/ and also on every chef it's been uploaded to. The safest way is really to bump the version number to 6.1.4 after reverting the changes.

**Comment by damacus** [comment]
Those versions have been pulled from the supermarket. I will publish a new version to supermarket once I can sit down and publish `6.1.4` based off `6.1.1` tomorrow.

**Comment by damacus** [comment]
Good news. 

v6.1.4 has been released to the supermarket now, branched from v6.1.1 with the additional deprecations in the cookbook. 

Apologies for all in inconvenience caused!
