### ISSUE TITLE
Postgresql Server Config: additional_config ignored 

### ISSUE THREAD

**Issue by jimdaga** [sous-chefs/postgresql#539]
### Cookbook version
7.0.0

### Chef-client version
14.1.12

### Platform Details
Ubuntu 16.04.4 LTS

### Scenario:
I'm testing out the new 7.0.0 cookbook and looking to use the 'postgresql_server_conf' resource with the 'additional_config' property to update the postgresql.conf file with extra settings. 

It looks as if the additional_config hash is empty by the time the template is applied, so none of the extra configs are being set in the postgresql.conf file. 

### Steps to Reproduce:

Recipe 
```
postgresql_server_install 'My Postgresql Server install' do
  version '9.6'
  action :install
end

postgresql_server_conf 'My PostgreSQL Config' do
  version '9.6'
  additional_config = {
    'listen_addresses'  => '*',
    'max_connections'   =>  '500'
  }
end
```

Note:
Same thing happens using the : format for the hash:
```
  additional_config = {
    'listen_addresses':  '*',
    'max_connections':   '500'
  }
```

### Expected Result:
Expect the following two settings to be added to the postgresql.conf file. 
```
listen_addresses  = '*',
max_connections  =  '500'
```

### Actual Result:
Only the values that have default values are added to the config. 
```
# cat /etc/postgresql/9.6/main/postgresql.conf
# PostgreSQL configuration file
# This file was automatically generated and dropped off by chef!
# Please refer to the PostgreSQL documentation for details on
# configuration settings.

# PostgreSQL configuration file
# This file was automatically generated and dropped off by chef!
# Please refer to the PostgreSQL documentation for details on
# configuration settings.

data_directory = '/var/lib/postgresql/9.6/main'
hba_file = '/etc/postgresql/9.6/main/pg_hba.conf'
ident_file = '/etc/postgresql/9.6/main/pg_ident.conf'
external_pid_file = '/var/run/postgresql/9.6-main.pid'
stats_temp_directory = '/var/run/postgresql/9.6-main.pg_stat_tmp'
```

these values remain default:
```
postgres=# show listen_addresses;
 listen_addresses
------------------
 localhost
(1 row)

postgres=# show max_connections;
 max_connections
-----------------
 100
(1 row)
```

### Extra Notes:
I tested updating the template and removing the extra logic and additonal_config was still Nil.
```
<% @additional_config.sort.each do |key, value| %>
<%= key %> = <%= value %>
```

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. Right now this issue is blocked behind #535.

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by jimdaga** [comment]
Understood, thanks for the update @damacus. I'll take a little more of a look Monday and see if I can be of any help, and will be sure to message in #sous-chef if needed.

Thanks,
Jim

**Comment by damacus** [comment]
Excellent, thanks for the help!

As you can see #535 is proving to be a little bigger than I'd like

**Comment by jimdaga** [comment]
Ok, so it looks like this was a syntax issue in my wrapper cookbook. 
I was setting additional_config as a hash in the recipe.
```
  additional_config = {
    'listen_addresses'  => '*',
    'max_connections'   =>  '500'
  }
```

When it should be in this format.
```
  additional_config 'listen_addresses' => '*',
    'max_connections' => '500'
```

I have a feeling I was accidentally causing a hashed array of hashes in my original format. 

What are the communities thoughts on having the README example updated to include this syntax? I'd be happy to handle that however small it is.

**Comment by damacus** [comment]
The original hash will work if you do

Awesomenewhash = { stuff }

Postgres_config do
Extra_config Awesomenewhash
Enc

**Comment by jimdaga** [comment]
great, that format also works. Thanks @damacus.
