### ISSUE TITLE
PostgreSQL is not the latest version

### ISSUE THREAD

**Issue by davidfetter** [sous-chefs/postgresql#545]
### Cookbook version
All

### Chef-client version
All

### Platform Details
All

### Scenario:
Run the latest released version of PostgreSQL

### Steps to Reproduce:
1. Use the PostgreSQL cookbook
2. Log onto the node
3. psql -U postgres -AtXc 'SELECT version()'

### Expected Result:
PostgreSQL 10...

### Actual Result:
PostgreSQL 9.6...

### Proposed fix:
GH-544

**Comment by damacus** [comment]
Looks like you haven't specified version 10 of postgresql, and just left the defaults?
