### ISSUE TITLE
pg_hba should not set defaults first

### ISSUE THREAD

**Issue by skadz** [sous-chefs/postgresql#551]
### Cookbook version
7.1.0

### Chef-client version
Chef 14

### Platform Details
CentOS

### Scenario:
The default HBA has the lines:

`
local   all             postgres                                peer
local   all             all                                     peer
`

As the pg_hba is read in order, I cannot override any of the default settings.  I regularly need system users to access DBs as other users (ie httpd user on the system needs to access a DB as www) via the local socket and due to this setting being at the top of the file, I cannot do that.

There should either be a way to completely turn off the default or the defaults should be at the end of the file and as a user I set the rules I need first.

**Comment by damacus** [comment]
That sounds super sensible. I'd be open to options/configurations to deal with this scenario. 

Leaving this as the default is fine, but being able to turn it off, and configuring everything is really needed.

**Comment by skadz** [comment]
Threw a PR in here:

https://github.com/sous-chefs/postgresql/pull/552

**Comment by damacus** [comment]
As pr discussion in the pr, closing this issue. Thanks taking your time to open an issue!
