### ISSUE TITLE
postgresql_server_conf modify in original file.

### ISSUE THREAD

**Issue by mddubey** [sous-chefs/postgresql#553]
### Cookbook version
7.1.0

### Chef-client version
 chef-solo --version => 14.2.0

### Platform Details
Ubuntu 16.04.5 LTS

### Scenario:
I was using `postgresql_server_conf` to update conf file with `listen_addresses` and few other configs and it deletes every other configuration, even the ones which come by default with postgres. How can I use it just modify the lines which are given and not replace the whole file?

Thank you

**Comment by damacus** [comment]
In this case you want to use the line cookbook to edit the files. We maintain the entire file with this cookbook, which is common practise, so that one config knows it's setting the correct variables, and not having it's work undone a few lines laer by another program.
