### ISSUE TITLE
Resource to execute SQL

### ISSUE THREAD

**Issue by gionn** [sous-chefs/postgresql#554]
It would be great to have a generic resource that executes arbitrary SQL commands (I am currently missing how to create a read-only role to access a database).

**Comment by damacus** [comment]
Hi @gionn , 

we're not looking at providing this sort of functionality from this cookbook, as this is usually down to an application specific implementation (such as creating a read-only user).

**Comment by gionn** [comment]
I was thinking about a generic `sql_query` resource to execute raw queries instead of doing something like:

```
  sql_grants = [
    "GRANT CONNECT ON DATABASE #{database_name} TO #{ro_user};",
  ]

  sql_grants.each do |query|
    execute query do
      command "psql #{database_name} -c '#{query}'"
      user 'postgres'
      action :nothing
      subscribes :run, "postgresql_user[#{ro_user}]", :immediately
    end
```

I am pretty sure that previous versions of the cookbook had something for this purpose.

**Comment by damacus** [comment]
That sounds like a generic resource that doesn't belong in this cookbook, but a generic resource that can be reused across cookbooks.

Closing as a "won't fix", we this isnt a feature we're looking at developing in the postgresql cookbook.

Feel free to drop by the sous-chefs slack channel to continue this conversation!
