### ISSUE TITLE
 service[postgresql]: Service is not known to chkconfig.

### ISSUE THREAD

**Issue by jdnrg** [sous-chefs/postgresql#562]
It seems that we need to support systemd as well.

### Cookbook version
cookbook 'postgresql', '~> 7.1.0'

### Chef-client version
chef_version=14.4.56

### Platform Details
platform=centos
platform_version=7.5.1804
running in docker on windows 10

### Scenario:
Install postgres

### Steps to Reproduce:
```
postgresql_server_install 'postgresql 9.6 server' do
  password pgaccount['password']
  version '9.6'
  port 5433
  action :create
end
```

### Expected Result:

```
systemctl enable postgresql-9.6.service
````
see https://wiki.postgresql.org/wiki/PostgreSQL_on_RedHat_Linux

### Actual Result:

```
      * service[postgresql]: Service is not known to chkconfig.
             ================================================================================
             Error executing action `enable` on resource 'service[postgresql]'
             ================================================================================

             Chef::Exceptions::Service
             -------------------------
             service[postgresql]: Service is not known to chkconfig.

             Resource Declaration:
             ---------------------
             # In

       60:   service 'postgresql' do
       61:     service_name platform_service_name
       62:     supports restart: true, status: true, reload: true
       63:     action [:enable, :start]
       64:   end
       65:
```

**Comment by damacus** [comment]
Hi the service won't be called this, but whatever, platform_service_name is called, due to it being different for every platform. 

An example of how to do this can be seen here: 
https://github.com/sous-chefs/postgresql/blob/master/test/cookbooks/test/recipes/access.rb#L32-L37
