### ISSUE TITLE
hardcoded database name

### ISSUE THREAD

**Issue by jdnrg** [sous-chefs/postgresql#563]
https://github.com/sous-chefs/postgresql/blob/1ca7b92a95fea927ed564c938031028c3f658287/resources/extension.rb#L31
do we not need to pass in the database name here?

**Comment by gionn** [comment]
yes, that's a great bug, next time it's better to write tests with a different database name :rofl:

**Comment by damacus** [comment]
Thanks for your comments on this one :) 

We'd love some more PRs to fix these sorts of issues if you spot them. Secondly, if you notice that some PRs don't have "ideal" tests, you can get involved with the community and increase the quality of this cookbook.
