### ISSUE TITLE
PostgreSQL 10+ Work

### ISSUE THREAD

**Issue by curiositycasualty** [sous-chefs/postgresql#569]
### Cookbook version
`7.1.1`

### Chef-client version
`14.5.33`

### Platform Details
`Ubuntu` `16.04`/`18.04`

### Scenario:
Attempting to use this cookbook to install/run PostgreSQL 10.5. There are some assumptions here about the shape of the `postgresql` service that aren't and will not be true for versions later than 9.x. One big one is that Debian/Ubuntu (apt) have moved away from setting up a generic `postgresql` systemd service unit. Instead, you get `pg_ctl` and (on Debuntu) `pg_lsclusters` which are supposed to accommodate several "clusters" of different versions of the service. Getting the "status" of one of these "clusters" for example, looks like this (where "10" is the postgres version, and "main" is the default name of the first "cluster"): `pg_lsclusters (--skip-systemctl-redirect) 10 main status`.

At this juncture, it probably makes sense to bump up to a "version 8" of this cookbook to accommodate the newer versions of PostgreSQL and their assumptions.

**Comment by leegarrett** [comment]
I think your description is a bit inaccurate. Debian/Ubuntu moved away from a generic postgresql systemd unit to a *template* systemd unit, which accept arguments. So instead of 'systemctl restart postgresql', you can now do 'systemctl restart postgresql@9.5' to restart your 9.5 cluster.

pg_ctl and pg_lsclusters have existed for at least 7 years now, those are not new and AFAICS nothing has changed in that regard.

I think it would be more helpful to show actual problems you run into when provisioning machines with postgresql 10 and file individual bug reports.

**Comment by curiositycasualty** [comment]
To be clear: the cookbook works as is, for what seems like the intended use case: standing up a single instance of Postgres running a single version of Postgres.

Where I think it falls over is when you want to address any of the "edge" cases like:
  - multiple instances of postgres running on a single OS or
  - multiple instances of postgres running different versions (of Postgres) on a single OS

This issue is to address the underlying assumptions of the cookbook that make these "edge" cases difficult. Namely, this cookbook doesn't surface the management abstractions like "cluster" or the `systemd` templated units that you referenced; despite those abstractions existing on Debian/Ubuntu systems "for at least 7 years now."

**Comment by leegarrett** [comment]
Then I'd file a bug with a feature request for supporting multiple clusters. Since that would change the semantics for all resources, I'd expect it to bump the version number to 8.0.0.

**Comment by damacus** [comment]
Both of you probably need #523

**Comment by ramereth** [comment]
@curiositycasualty is this still an issue?

**Comment by curiositycasualty** [comment]
Haven't been able to upgrade past the version of the cookbook we currently use.
But this can probably be closed.
