### ISSUE TITLE
Too strict postgresql.conf permissions for ident auth

### ISSUE THREAD

**Issue by Aketzu** [sous-chefs/postgresql#574]
Debian 9.5, Postgres 10.5-2.pgdg90+1

Ident authentication doesn't seem to work,
```
$ psql
Error: Invalid data directory for cluster 10 main
```
Simple fix is to chmod a+r /etc/postgresql/10/main/postgresql.conf

Any reason why it is limited here?
https://github.com/sous-chefs/postgresql/blob/1d66a9b22e9e116b4e27766446fbf30ba26b1066/resources/server_conf.rb#L37

In default Debian packages file is 0644 so I don't see any real reason to limit world-readability

**Comment by josephholsten** [comment]
@Aketzu sounds like something that should be improved! Care to throw together a PR for us to review and we'll get it out there?

**Comment by aried3r** [comment]
Is this a duplicate of #588 which has been resolved in #589?

**Comment by Aketzu** [comment]
Seems so. Closing this.
