### ISSUE TITLE
postgresql_user fails on username with dash

### ISSUE THREAD

**Issue by asasmoyo** [sous-chefs/postgresql#583]
### Cookbook version

7.1.1

### Chef-client version

Not sure what's the version but here's my [Gemfile.lock](https://pastebin.com/tnw7R2Gu)

### Platform Details

Ubuntu 18.04 in GCP

### Scenario:

I want to create database user with dash `-` in username but failed.

Example username value: `api-staging`

### Steps to Reproduce:

```
execute("create postgresql user api-staging") do
  action [:run]
  default_guard_interpreter :execute
  command "/usr/bin/psql -c \"CREATE ROLE api-staging WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION LOGIN ENCRYPTED PASSWORD 'password'\" -U postgres --port 5432"
  backup 5
  returns 0
  user "postgres"
  declared_type :execute
  cookbook_name "database"
  domain nil
  sensitive false
  not_if { #code block }
end
```

### Expected Result:

User created

### Actual Result:

```
execute[create postgresql user api-staging] (/home/arba/chef-solo/local-mode-cache/cache/cookbooks/postgresql/resources/user.rb line 40) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/psql -c "CREATE ROLE api-staging WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION LOGIN ENCRYPTED PASSWORD 'password'" -U postgres --port 5432 ----
    STDOUT: 
    STDERR: ERROR:  syntax error at or near "-"
    LINE 1: CREATE ROLE api-staging WITH NOSUPERUSER NOCREATEDB NOCREATE...
```

It seems username does not get escaped so query fails

**Comment by damacus** [comment]
Hy,
thanks for the report. 

What happens if you install the database normally and run this query agains the DB manually?

**Comment by asasmoyo** [comment]
Hey :)

I can confirm running above resulting query directly to database fails. The username value needs to be escaped with double quote, ex: `"username"`. I tried adding the double quote to the query and it worked.

Here's the working query

```
/usr/bin/psql -c "CREATE ROLE \"api-staging\" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION LOGIN ENCRYPTED PASSWORD 'password'" -U postgres --port 5432
CREATE ROLE
```

**Comment by damacus** [comment]
If you can figure out how to get that into the existing code and the existing create user test we'd love to have this PR in!

**Comment by asasmoyo** [comment]
Sorry it took me a while to do this. I just created a pr, please check it later :)
