### ISSUE TITLE
Mode 600 is restrictive

### ISSUE THREAD

**Issue by jmikedupont2** [sous-chefs/postgresql#588]
The setting of the postgres.conf mode to 600 makes it not readable by the psql client.
`Error: Invalid data directory for cluster 9.6 main` is what I get when running psql as a normal user
strace shows 
```
open("/usr/lib/postgresql/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/etc/postgresql/9.6/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
``` 
This is set in the file
https://github.com/sous-chefs/postgresql/blob/38915d62d922374bbc4d2363306d8ac1cd81baaf/resources/server_conf.rb#L37

Best practices state:
`All the conf files should be owned by the postgres user, and the configuration files should be world-readable if possible (indeed, it’s a requirement for Debian based system that postgresql.conf be readable for psql to work!).`
https://www.endpoint.com/blog/2010/09/27/postgres-configuration-best-practices

I would suggest a 644

**Comment by damacus** [comment]
Fixed by #589
