### ISSUE TITLE
Overriding the postgresql_access template?

### ISSUE THREAD

**Issue by homerlex** [sous-chefs/postgresql#610]
### Cookbook version
postgressql 7.1.4

### Chef-client version
14.1.12

### Platform Details
bonic64 (Unbuntu 18)

The documentation for postgresql_access states the you can specify a "source" to override the pg_hba.conf.erb that is being used.  How do I get it to find the template that I created in my cookbook?  It seems to only be searching for templates in the postgesql cookbook.

I have something like the following:
```
postgresql_access 'Host machine Postgres Access' do
  source 'my_pg_hba.conf.erb'
  access_type 'host'
  access_db 'all'
  access_user 'all'
  access_addr '10.0.0.0/16'
  access_method 'trust'
end
```
I have the my_pg_hba.conf.erb file in my cookbook's template directory.  I get the following error:

```
[2019-06-11T20:12:18+00:00] FATAL: Chef::Exceptions::FileNotFound: template[/etc/postgresql/11/main/pg_hba.conf] (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/dsl/declare_resource.rb line 158) had an error: Chef::Exceptions::FileNotFound: Cookbook 'postgresql' (7.1.4) does not contain a file at any of these locations:
  templates/ubuntu-18.04/my_pg_hba.conf.erb
  templates/ubuntu/my_pg_hba.conf.erb
  templates/default/my_pg_hba.conf.erb
  templates/my_pg_hba.conf.erb

This cookbook _does_ contain: ['templates/pg_ident.conf.erb','templates/postgresql.service.erb','templates/postgresql.conf.erb','templates/pg_hba.conf.erb','templates/pgsql.sysconfig.erb']
```

**Comment by Xorima** [comment]
you need to set the cookbook as well :) its a property

**Comment by homerlex** [comment]
Dang, how did I miss that? Thanks @Xorima
