### ISSUE TITLE
Error on postgresql_user action:drop

### ISSUE THREAD

**Issue by PhilippeBerard** [sous-chefs/postgresql#629]
### :speaking_head: Foreword

To deploy our customers' SaaS applications, we use this cookbook for creating the corresponding database and database user.

## :ghost: Brief Description

After droping a database, droping the user systematically fails with a "ShellCommandFailed: Command execution failed". Droping the user manually works flawlessly.
 
## :pancakes: Cookbook version

7.1.4

## :woman_cook:  Chef-Infra Version

14.11.21

## :tophat: Platform details

Debian 9 Stretch
Kernel 4.9.0-9-amd64
Linux jalios29 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux

## Steps To Reproduce

1/ Create User
2/ Create Database
3/ Delete Database
4/ Delete User
5/ ERROR

## :police_car: Expected behavior

Database user dropped without error.

## :heavy_plus_sign: Additional context

The machines where the error occur handle Apache2 websites, Tomcat 8 webapps with OpenJDK 8.

**Comment by PhilippeBerard** [comment]
Would it be possible to have any return on this issue ? Thanks.

**Comment by damacus** [comment]
Hey @PhilippeBerard sorry about the the lack of response on this issue, and thanks for sending a reminder. 

Are you able to write a test in a PR to show the error? That way we have an test that we can confirm works to stop future regression. Thanks!

**Comment by JonBetts** [comment]
I'm getting an issue dropping users on version 7.1.9 of the cookbook. Looks like it is putting single quotes around the user/role name in the statement:

```
---- Begin output of /usr/bin/psql -c "DROP ROLE IF EXISTS 'jon'" -U postgres --port 5432 ----
STDOUT: 
STDERR: ERROR:  syntax error at or near "'jon'"
LINE 1: DROP ROLE IF EXISTS 'jon'
                            ^
---- End output of /usr/bin/psql -c "DROP ROLE IF EXISTS 'jon'" -U postgres --port 5432 ----
```

Not sure if this needs a test or anything, as it sounds like a potentially simple fix.

**Comment by Zhann** [comment]
> I'm getting an issue dropping users on version 7.1.9 of the cookbook. Looks like it is putting single quotes around the user/role name in the statement:
> 
> ```
> ---- Begin output of /usr/bin/psql -c "DROP ROLE IF EXISTS 'jon'" -U postgres --port 5432 ----
> STDOUT: 
> STDERR: ERROR:  syntax error at or near "'jon'"
> LINE 1: DROP ROLE IF EXISTS 'jon'
>                             ^
> ---- End output of /usr/bin/psql -c "DROP ROLE IF EXISTS 'jon'" -U postgres --port 5432 ----
> ```
> 
> Not sure if this needs a test or anything, as it sounds like a potentially simple fix.
> 
> In case it helps, I'm on Chef 13.12.14 and Postgres 12.

you're right, the fix would be easy: https://github.com/sous-chefs/postgresql/pull/661
