### ISSUE TITLE
Add properties to allow people to specify a local repo instead of only using the remote postgres one

### ISSUE THREAD

**Issue by louraz** [sous-chefs/postgresql#662]
### :speaking_head: Foreword

I want to be able to specify an internal company repo instead of going to the external Postgres website. 

##  Problem Statement

My company does not allow external links to be used during builds as it compromises security.

## :grey_question: Possible Solution

Suggest new properties are added to allow this including the repo address and keys addresses

## :arrow_heading_up: Describe alternatives you've considered

Otherwise I will have to pull this cookbook and edit it, I would prefer to be able to add a wrapper cookbook to pass in the properties

**Comment by ramereth** [comment]
@louraz You're welcome to create a PR which adds this feature! Let us know if you need any help.

**Comment by louraz** [comment]
Hi, closing this, I managed to make it work by specifying   setup_repo false which is a little counter intuitive but it did what I needed.

**Comment by ramereth** [comment]
@louraz FWIW this topic was brought up during our weekly Sous Chefs meeting by @nvwls as he was something similar standardized across our cookbooks for air gap environments.

@nvwls We may want to re-open this and use this as an initial go for standardizing this for other cookbooks. This cookbook is already resource driven, so it's a good candidate to try.
