### ISSUE TITLE
Unable to connect to an RDS instance from AWS because of lack of password

### ISSUE THREAD

**Issue by WillRogers727** [sous-chefs/postgresql#689]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

I am currently updating some chef scripts that used to use the database cookbook to set up a rails app and postgres 12 database on an AWS RDS instance. As the database cookbook was depreciated and the code no longer worked for Postgres 12, I updated the code to use this cookbook instead.

I need to connect to the RDS instance, and create the db.

The issue is that I am unable to connect to the RDS instance because postgresql_database doesn’t have a password field, so I am left hanging when it runs the script at the stage where the RDS instance asks for a password.

## :pancakes: Cookbook version

8.3.0

## :woman_cook:  Chef-Infra Version

13.12

## :tophat: Platform details

Ubuntu 18.04

## Steps To Reproduce

```
		adapter = 'postgresql'

      node.run_state['postgresql'] ||= {}
      node.run_state['postgresql']['version'] = '12'

      postgresql_client_install 'PostgreSQL Client install' do
        version '12'
      end

      postgresql_server_install 'My PostgreSQL Server install' do
        action :install
      end

      postgresql_user database_config['username'] do
        createdb true
        action :create
      end

      postgresql_database database_config['database'] do
        host database_config['host'] # RDS hostname
        user database_config['username'] # this is just postgres user usually
        port database_config['port'].to_i
        action :create
      end
```

## :police_car: Expected behavior

The database to create (when a password is present)

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by agarwalhanoo** [comment]
We can use the environment variable PGPASSWORD to solve this problem for us. Also saving the password in .pgpass file would also solve this problem. When Chef-Client runs, it would directly take the password from the environment variable and will do the authentication. 
This way you could create databases and user on AWS RDS using this cookbook.

**Comment by agarwalhanoo** [comment]
@WillRogers727   We can use the environment variable PGPASSWORD to solve this problem for us. Also saving the password in .pgpass file would also solve this problem. When Chef-Client runs, it would directly take the password from the environment variable and will do the authentication.
This way you could create databases and user on AWS RDS using this cookbook.
