### ISSUE TITLE
certificate verify failed (certificate has expired) - https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

### ISSUE THREAD

**Issue by manush1985** [sous-chefs/postgresql#697]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Unable to install Postgresql server or client because cookbook is not able to download binaries from download.postgres.org because of expired certificate ( I assue this is related to recent Letsencrypt root certificate expiration ) 

OpenSSL::SSL::SSLError
 ----------------------
remote_file[/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG] (/tmp/kitchen/cache/cookbooks/postgresql/resources/repository.rb line 34) had an error: OpenSSL::SSL::SSLError: SSL Error connecting to https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG - SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

## :pancakes: Cookbook version

9.0.3

## :woman_cook:  Chef-Infra Version

Chef Kitchen version: 2.2.5 
Chef version: 16

## :tophat: Platform details

Operating system: Windows
Chef --> Kitchen --> Vagrant box --> CentOS-7.9 and CentOS-7.8

## Steps To Reproduce

Just try coverging the recipe with the above environment and you willl see the error.

## :police_car: Expected behavior

Postgres instance will be created normally.

## :heavy_plus_sign: Additional context

NA.

**Comment by manush1985** [comment]
Looks like this is the root cause.

Chef remote_file resource is using its own CA trust store and expried Letsencrypt root certificate (DST CA X3) is not yet removed for this store. Hence, remote_file resource fails to connect securely to download.postgresql.org. 

When ssl_verify_mode is set to :verify_none, then it works. Without this, it doesn't

remote_file "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-12" do
  source 'https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG'
  ssl_verify_mode :verify_none
end

Anyone knows how remote_file resource gets a list of all trusted root CA certs? I don't think it depends on Linux because I have already updated Linux ca certs to not include the expired letsencrypt root cert.

**Comment by hrak** [comment]
chef infra client 17.6.18 & 16.16.13 fix this issue
