### ISSUE TITLE
postgresql_access raises `NoMethodError: undefined method `named_captures' for nil:NilClass`

### ISSUE THREAD

**Issue by rottenbytes** [sous-chefs/postgresql#714]
Hi !

I noticed that when adding entries in pg_hba.conf using the `postgresql_access` resources, if there are entries where username contains a `.` then an exception is raised because parsing fails

Stacktrace is : 
```
    NoMethodError
    -------------
    undefined method `named_captures' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/libraries/access.rb:155:in `block in split_entries'
    /var/chef/cache/cookbooks/postgresql/libraries/access.rb:155:in `map!'
    /var/chef/cache/cookbooks/postgresql/libraries/access.rb:155:in `split_entries'
    /var/chef/cache/cookbooks/postgresql/libraries/access.rb:89:in `read!'
    /var/chef/cache/cookbooks/postgresql/libraries/access.rb:139:in `read'
    /var/chef/cache/cookbooks/postgresql/resources/access.rb:64:in `block in class_from_file'
```

I've been testing the regex at  https://github.com/sous-chefs/postgresql/blob/main/libraries/access.rb#L73 against my config file using rubular and it's not matching

Thanks for your help !

**Comment by bmhughes** [comment]
The old regex adage is proving true thus far, could you give a few examples of what doesn't work and I'll look into fixing it.

**Comment by rottenbytes** [comment]
Adding a line such as
```
host	feature_event		first.last		10.0.0.0/8		md5
```

into `pg_hba.conf` triggers the issue. Commented it and run went smoothly
