### ISSUE TITLE
cleartext postgres password

### ISSUE THREAD

**Issue by timor-raiman** [sous-chefs/postgresql#95]
(using chef-solo)

In the README it says that node['postgresql']['password']['postgres'] must be a hash of the real password (in the format md5#{some_string_of_hex})

Expected behaviour:
Setting node['postgresql']['password']['postgres'] to a string which does not begin with 'md5' disables interactive password access.

Observed behaviour:
When I set the password to some random string (eg: bb77d0d3b3f239fa5db73bdf27b8d29a, which happens to lack the 'md5' prefix), I can use this string clear text on the interactive password prompt of psql.

Solutions:
Document this behaviour?
Remove this functionality?

**Comment by feitingen** [comment]
This is still undocumented and/or broken.

**Comment by jmadden-igodigital** [comment]
The current behavior is dangerous-by-default.  In other words, setting the password and storing it in the node object is dumb, bad, and shouldn't be done at all by default, it should be behavior that's enabled manually if at all.  Storing passwords on node objects is a huge security hole whether or not they're plain text.  From a security posture I'd rather have no password at all (i.e., prevent remote logins altogether) than have some password set that I'm not even aware of having been set that's then stored on the node object, in the chef server, and wherever else you're storing node objects (backups, your SCM, etc.).  

I mean, good grief, seriously?

**Comment by shortdudey123** [comment]
@jmadden-igodigital you are more than welcome to submit a PR to support encrypted data bags :)
Otherwise someone can do it when they have a chance to work with it

**Comment by xamebax** [comment]
@jmadden-igodigital I understand security is important for all of us, but in reply to the tone of your comment, I would like to point you to the Community Guidelines this cookbook quotes in its Code of Conduct:

> As you are working with other members of the community, please keep in mind the following guidelines, which apply equally to founders, mentors, those who submit new features and pull requests, and to anyone who is seeking help and guidance.
> 
> The following list isn’t exhaustive; it is intended to help all of us communicate well so that the community can work better together:
> 
>     Be welcoming, inclusive, friendly, and patient.
>     Be considerate.
>     Be respectful.
>     Be professional.
>     Be careful in the words that you choose.
>     When we disagree, let’s all work together to understand why.
> 
> The previous list applies to all forms of communication: slack, the mailing list, the issue tracker, and any other forum that is used by the community.
> 
> Please keep in mind that:
> 
>     Your work will be used by other people, and you, in turn, will depend on the work of others.
>     Decisions that you make will often affect others in the community.
>     Disagreements happen, but should not be an excuse for poor behavior and bad manners. When disagreements do happen, let’s work together to solve them effectively and in a way that ensures that everyone understands what the disagreement was.
>     People may not understand jokes, sarcasm, and oblique references in the same way that you do. So remember that and be kind to the other members of the community.

**Comment by josephholsten** [comment]
@jmadden-igodigital I’ve heard a few people express reluctance to keep passwords in chef, and haven’t quite understood the threat model that concerns people. I don’t want to continue this conversation on this ticket, but I’d love to chat with you about in the chef community slack if you have a chance.

**Comment by timor-raiman** [comment]
A better solution would be to be able to provide the password as an option to (all of) the relevant resources and not as an attribute on the node.
Node attributes are visible to all users / machines.
A resource option on the other hand can be provided during chef run, after chef-client looks it up in the chef-vault, which is access-controlled and limited to the machines that are allowed access to the particular vault.
This ticket, however is about the discrepancy between implementation and the docs.. it's not about what's the best way to handle passwords...

**Comment by jmadden-igodigital** [comment]
I meant this actually for both issues, that node objects are readable by every other node and about the doc discrepancy, but feel free to use either motive to resolve the underlying problem. From a general security posture we shouldn't set passwords that admins aren't required to be aware of (no password at all with no open network socket is arguably better) and we shouldn't store them in plain text (regardless of the medium) unless, again, the admin forces the situation.

**Comment by damacus** [comment]
This is now fixed as part of master, we no longer save the password to the node data using node.save.
